config/routes.rb
Footballmapper::Application.routes.draw do
  get "static/index"

  get "advertisers/new"

  devise_for :advertisers

  get "leagues/new"

  get "league/new"

  get "search" => "schools#search"

  resources :schools

  resources :leagues

  root :to => "schools#index"


end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :advertisement, :business_name, :city, :last_name, :first_name, :state, :street, :url, :zipcode, :school_id

  belongs_to :school

  acts_as_gmappable 

  def gmaps4rails_address
   "#{city}, #{state}"
  end

  def school
    School.advertiser
  end

end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :name

  has_many :schools
end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :big_game, :content, :division, :globe_rank, :herald_rank, :highly_recruited, :latitude, :longitude, :losses, :name, :pts_against, :pts_for, :wins, :league

  has_one :advertiser

  acts_as_gmappable :process_geocoding => false

  def self.search(search)
    if search
      find(:all, :conditions => ["name LIKE ?", "%#{search}%"])
    else
      find(:all)
    end
  end

  def gmaps4rails_address
   "#{name}, #{state}"
  end
end

app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController
  
  def index
    @advertisers = Advertiser.all
  end

  def show
    @advertiser = Advertiser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advertiser }
    end
  end

  def new
    @advertiser = Advertiser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advertiser }
    end
  end

  def edit
    @advertiser = Advertiser.find(params[:id])
    @first = Advertiser.first
    @json = @advertiser.to_gmaps4rails
  end

  def create
    @advertiser = Advertiser.new(params[:advertiser])

    respond_to do |format|
      if @advertiser.save
        format.html { redirect_to @advertiser, notice: 'Advertiser was successfully created.' }
        format.json { render json: @advertiser, status: :created, location: @advertiser }
      else
        format.html { render action: "new" }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @advertiser = Advertiser.find(params[:id])

    respond_to do |format|
      if @advertiser.update_attributes(params[:advertiser])
        format.html { redirect_to @advertiser, notice: 'Advertiser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @advertiser = Advertiser.find(params[:id])
    @advertiser.destroy

    respond_to do |format|
      format.html { redirect_to advertisers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all
  end

  def show
    @league = League.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @league }
    end
  end

  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  def edit
    @league = League.find(params[:id])
  end

  def create
    @league = League.new(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @league = League.find(params[:id])

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
    @json = @schools.to_gmaps4rails do |school, marker|
    marker.infowindow render_to_string(:partial => "infowindow", :locals => { :school => school})
    marker.title "#{school.name}"
    marker.json({ :content => school.content, :division => school.division, :wins => school.wins,
                  :losses => school.losses, :pts_for => school.pts_for,
                  :globe_rank => school.globe_rank, :herald_rank => school.herald_rank,
                  :pts_against => school.pts_against, :big_game => school.big_game, 
                  :highly_recruited => school.highly_recruited, :league => school.league                  
                })
    marker.picture({:picture => "http://www.kilmain.com/gmaps_icons/usfootball_default2.png",
                    :width => 32,
                    :height => 32
                    })
    end
  end

  def search
    @schools = School.search(params[:search])
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/league_helper.rb
module LeagueHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/advertisers/index.html.erb
<h1>leagues</h1>
<br>
<% @leagues.each do |league| %>
  <p>Name: <%= league.name %> | ID: <%= league.id %></p>
<% end %>
<%= link_to 'New', new_league_path %>

app/views/advertisers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @league.name %>
</p>


<%= link_to 'New', new_league_path %>
<%= link_to 'Back', leagues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FootballMapper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= yield :scripts %>

</body>
</html>

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/new.html.erb
<h1>New Leauge</h1>
<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/schools/_about_dialog.html.erb
<p>Football. Maps. FootballMapper. </p>
<p>Footballmapper is for high school football players, fans, scouts, parents, coaches - anyone involved or interested in Massachusetts high school football. </p>
<p>Our aim is to make finding relevant content easy and fun. We have sliders so that you can query teams. We have a twitter feed for real time game updates. We have a youtube feed so that you can link to game highlights.</p> 
<p>Our advertisers are real small businesses who update advertisements frequently. They usually display content directly related to an upcoming game. I hope you find the advertisements usefull. If you found a great place through an advertisement on Footballmapper please let me know!</p>
<hr>
<p><img src="assets/george150.jpg" style="float:left; margin: 10px 10px 10px 0;" /> Who developed Footballmapper? Hi, let me introduce myself: My name is George Kilmain. I am a web developer, pasionate football fan, and lover of maps.</p>
<p>Web application specs: This is a Ruby on Rails app. It uses the Google Maps API, Twitter API, Youtube API, Bootstrap, and various jQuery UI widgets.</p>  

app/views/schools/_contact_dialog.html.erb
<h2>contact!</h2>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :wins %><br />
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :losses %><br />
    <%= f.number_field :losses %>
  </div>
  <div class="field">
    <%= f.label :pts_for %><br />
    <%= f.text_field :pts_for %>
  </div>
  <div class="field">
    <%= f.label :pts_against %><br />
    <%= f.text_field :pts_against %>
  </div>
  <div class="field">
    <%= f.label :division %><br />
    <%= f.number_field :division %>
  </div>
  <div class="field">
    <%= f.label :league_id %><br />
    <%= f.number_field :league_id %>
  </div>
  <div class="field">
    <%= f.label :big_game %><br />
    <%= f.check_box :big_game %>
  </div>
  <div class="field">
    <%= f.label :highly_recruited %><br />
    <%= f.check_box :highly_recruited %>
  </div>
  <div class="field">
    <%= f.label :globe_rank %><br />
    <%= f.number_field :globe_rank %>
  </div>
  <div class="field">
    <%= f.label :herald_rank %><br />
    <%= f.number_field :herald_rank %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/_infowindow.html.erb
<div id="bheader">
	<div class="headerContent"><%= school.name %> High School |</div> 
	<div class="headerContent">Record: <%= school.wins %> &#8211;<%= school.losses%> |</div>
	<div class="headerContent">Off: <%= school.pts_for %> Def: <%= school.pts_against%></div>
	<div class="break" />
</div>
	<div id="contentBox"><p><b>2012 Recap:</b> <%= school.content %></p></div>
	<div id="advert_box">
		<% if school.advertiser %> 
		<%= school.advertiser.business_name %> <br />
		<%= school.advertiser.advertisement %><br />
		<a href="http://<%= school.advertiser.url %>"><%= school.advertiser.url %></a>
		<% else %>
			<p>Would you like to advertise here? Please <%= link_to "Sign Up", new_advertiser_registration_path %></p>
		<% end %>
	</div>
	<div id="bfooter">
	<p>see something wrong? Have a comment? <a href="#contact">Contact</a></p>
</div>

app/views/schools/_main_content.html.erb
<div class="main_content_container">
  <div id="show-hide" style="color: #0088cc;cursor: pointer;">
    Hide Panel
  </div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#show-hide').click(function() {
      $('.main_content').slideToggle(400, function() {
        if($(this).is(':visible')){
        $('#show-hide').text('Hide Panel');
      } else {
        $('#show-hide').text('Show Panel');
      }
      });      
    })
  })
</script>
  <nav id="nav-container">
    <%= link_to 'School Listing', schools_path, id: 'schools_link' %>
  </nav>
  <div class="clearfix"></div>
  <div class="main_content">
    <h1>Football Mapper</h1>
    <p>A Ruby on Rails application which uses Google Maps and jQuery to query a map. The map consists of eastern Massachusetts high school football teams.</p>
    <p>This app is hosted on Heroku and is <b>concept only</b>. There is an advertising component which lets businesses advertise on individual markers as well as an admin panel so that advertisers can update their pitch.</p>
    <p>Technologies used in building this app: Ruby on Rails, jQuery, Bootstrap.</p>    
  </div>
</div>
<!--
<div class="main_content_container">
  <span data-toggle="collapse" data-target=".main_content" style="cursor: pointer;text-decoration: underline;">Collapse</span>
  
  <ul class="nav nav-tabs">
    <li><a href="#home" data-toggle="tab">Home</a></li>
    <li><a href="#twit" data-toggle="tab">Twitter</a></li>
    <li><a href="#vids" data-toggle="tab">Videos</a></li>
  </ul>



  <div class="main_content collapse in" data-toggle="false">
    <div class="tab-content">
    <div class="tab-pane active" id="home">
      <p class="lead">A Quick Look Back to 2012</p>
      <p>Reading. Everett. St John's Prep. <i>Beverly</i>. Huh? Thats right: The Panthers were among the states perennial contenders finishing an impressive 13-0, beating Natick in the 2A Super Bowl. The Panthers were only one of three teams (Walpole and Lowell Catholic being the other two) to average scoring over 36 points while giving up less than 11. Beverly's Youtube video is featured under the video tab. Wow, awesome season Panthers!</p><p>Other stats worth noting: <b>Reading</b> was THE only team to give up less than a TD per game. Nasty! <b>Mansfield</b> had 5 losses (8 wins) including an early season route from the hands of <b>Stoughton</b> (9-2) but still made the Boston Globe Top 20. Whats up with that, Globe? Worst defense in Massachusetts? <b>Peabody</b>. The once proud program allowed an average of 42 points per game. Ouch.</p>
      <p>There are a lot more statistical anomalies you can find by using the sliders and checkboxes. See your results populated on the map. <b>2013 previews are right around the corner - stay tuned!</b></p>    
    </div>
    <div class="tab-pane" id="twit">
      <p class="lead">Twitta</p>
    </div>
    <div class="tab-pane" id="vids">
      <p class="lead">Videos</p>
      <iframe width="560" height="315" src="//www.youtube.com/embed/cAWLDUf0KFs" frameborder="0" allowfullscreen></iframe>
      <p>Beverly Panthers 2012 Youtube Video</p>
    </div>
  </div>
  </div>
</div>
-->

app/views/schools/_school_dialog.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag('/search', remote: true) %>
  <%= label_tag(:search, 'Search school:') %>
  <%= text_field_tag(:search) %>
<%= submit_tag("Find!") %>

<table style="text-align: center;" cellspacing="0" cellpadding="3" align="center" id="schools_table" class="tablesorter">
  <thead>
    <tr>
      <th style="text-align: left;">Name</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Points For</th>
      <th>Points Against</th>
      <th>Division</th>
      <th>Globe Rank</th>
      <th>Herald Rank</th>
    </tr>
  </thead>
  <tbody>
  <% @schools.each do |school| %>
  
    <tr>
      <td style="text-align: left;"><%= school.name %></td>
      <td><%= school.wins %></td>
      <td><%= school.losses %></td>
      <td><%= school.pts_for %></td>
      <td><%= school.pts_against %></td>
      <td><%= school.division %></td>
      <td><%= school.globe_rank %></td>
      <td><%= school.herald_rank %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/schools/_site_links.html.erb
  <p class="notice"><%= notice %></p>
  <% if advertiser_signed_in? %>
    <%= link_to "Admin Panel", edit_advertiser_registration_path, id: 'admin_panel_link' %>
    <%= link_to "Sign out", destroy_advertiser_session_path, :method => :delete %> 
  <% else %>
    <%= link_to "Sign in", new_advertiser_session_path %> |
  <% end %>
  <a href="#" id="schools_link">Schools</a> | <a href="#" id="about_link">About</a> | <a href="#" id="contact_link">Contact</a> 

app/views/schools/index.html.erb
<%= render 'main_content' %>
<div id="filter_wrapper">
      <h3>Now filtering: 2012 Data</h3>
      <p>Wins</p>
            <input type="text" id="filtered-wins" />
            <div class="break"></div>
            <div id='wins-range'></div>
            <br>
            <p>Losses</p>
            <input type="text" id="filtered-losses" />
            <div class="break"></div>
            <div id='losses-range'></div>
            <br>
            <p>Points Scored</p>
            <input type="text" id="filtered-points" />
            <div class="break"></div>
            <div id='points-range'></div>
            <br>
            <p>Points Against</p>
      <input type="text" id="filtered-points_against" />
      <div class="break"></div>
      <div id='points_against-range'></div>
      <br>
      <p>Boston Globe Top 20</p>
            <input type="text" id="filtered-globe" />
            <div class="break"></div>
            <div id='globe-range'></div>
            <br>
            <p>Boston Herald Sweet 16</p>
            <input type="text" id="filtered-herald" />
            <div class="break"></div>
            <div id='herald-range'></div>
            <br>
<!--            <input type="checkbox" id="big_game" />Big Game<br>
            <input type="checkbox" id="highly_recruited" />Highly Recruited
          -->
</div><!--filter wrapper-->
<!-- schools dialog window -->
<div id="schools_dialog">
  <%= render 'school_dialog' %>
</div>
<!-- about dialog window --> 
<div id="about_dialog">
  <%= render 'about_dialog' %>
</div>

<div id="contact_dialog">
  <%= render 'contact_dialog' %>
</div>

<%= gmaps(:markers => {:data => @json},
          :map_options => {:center_latitude => '42.231849', 
          :center_longitude => '-70.682591', :auto_adjust => false, :zoom => 9,
          :maxZoom => 12, :minZoom => 7}
         ) %> 
      
<% content_for :javascript %> 
<script type="text/javascript">
  $(document).ready(function() {
    Gmaps.map.callback = function() {

      // checkboxes :]
      // == BIG GAME STARTS HERE ==
      // Show big money er game!
      function showBigGame(big_game) {
        // console.log(gameInfo);
        for (var i=0; i<Gmaps.map.markers.length; i++) {
          if (Gmaps.map.markers[i].big_game ==  true) {
            Gmaps.map.showMarker(Gmaps.map.markers[i]);
          }
        }
        document.getElementById(big_game).checked = true;
      }

      // hides big games
      function hideBigGame(big_game) {
        for (var i=0; i<Gmaps.map.markers.length; i++) {
          if (Gmaps.map.markers[i].big_game == true) {
            Gmaps.map.hideMarker(Gmaps.map.markers[i]);
          }
        }
        // == clear the checkbox ==
        document.getElementById(big_game).checked = false;
        // == close the info window, in case its open on a marker that we just hid
        // Gmaps.map.infowindow.close();
      }

      // == HIGHLY RECRUITED STARTS HERE ==
      
      function showHighlyRecruited(highly_recruited) {
        // console.log(gameInfo);
        for (var i=0; i<Gmaps.map.markers.length; i++) {
          if (Gmaps.map.markers[i].highly_recruited ==  true) {
            Gmaps.map.showMarker(Gmaps.map.markers[i]);
          }
        }
        document.getElementById(highly_recruited).checked = true;
      }

      // hides big games
      function hideHighlyRecruited(highly_recruited) {
        for (var i=0; i<Gmaps.map.markers.length; i++) {
          if (Gmaps.map.markers[i].highly_recruited == true) {
            Gmaps.map.hideMarker(Gmaps.map.markers[i]);
          }
        }
        // == clear the checkbox ==
        document.getElementById(highly_recruited).checked = false;
        // == close the info window, in case its open on a marker that we just hid
        // Gmaps.map.infowindow.close();
      }
      
      // == BOX CLICK FUNCTIONS ==
      function bigGameBoxClick(box, big_game) { 
        if (box.checked) {
          showBigGame(big_game);
        } else {
          hideBigGame(big_game);
        }
      }

      function highlyRecruitedBoxClick(box, highly_recruited) {
        if (box.checked) {
          showHighlyRecruited(highly_recruited);
        } else {
          hideHighlyRecruited(highly_recruited);
        }
      }

      // click functions
      // big game!
      $('#big_game').click(function () {
        bigGameBoxClick(this, 'big_game');
      }); 

      // highly recruited
      $('#highly_recruited').click(function () {
        highlyRecruitedBoxClick(this, 'highly_recruited');
      }); 

      // == filters for sliders ==

      var WinsFilter = {
        min: 0,
        max: 13,
      };

      var LossesFilter = {
        min: 0,
        max: 12,
      };

      var PointsFilter = {
        min: 0,
        max: 45,
      };
    
    var PointsAgainstFilter = {
        min: 0,
        max: 45,
      };

      var GlobeFilter = {
        min: 0,
        max: 20,
      };

      var HeraldFilter = {
        min: 0,
        max: 16,
      };

      $( "#filtered-wins" ).val( (WinsFilter.min)+ " - " + (WinsFilter.max))

      $( "#filtered-losses" ).val( (LossesFilter.min)+ " - " + (LossesFilter.max))
      
      $( "#filtered-points" ).val( (PointsFilter.min)+ " - " + (PointsFilter.max))
      
      $( "#filtered-points_against" ).val( (PointsAgainstFilter.min)+ " - " + (PointsAgainstFilter.max))
      
      $( "#filtered-globe" ).val( (GlobeFilter.min)+ " - " + (GlobeFilter.max))
      
      $( "#filtered-herald" ).val( (HeraldFilter.min)+ " - " + (HeraldFilter.max))
      
      $("#wins-range").slider({
        range: true,
        min: WinsFilter.min,
        max: WinsFilter.max,
        values: [ WinsFilter.min, WinsFilter.max ],
        slide: function(event, ui) {
          $( "#filtered-wins" ).val( (ui.values[ 0 ])+ " - " + (ui.values[ 1 ]))
          WinsFilter.min = ui.values[ 0 ]
          WinsFilter.max = ui.values[ 1 ]
          applyFilters()
        }
      });

      $("#losses-range").slider({
        range: true,
        min: LossesFilter.min,
        max: LossesFilter.max,
        values: [ LossesFilter.min, LossesFilter.max ],
        slide: function(event, ui) {
          $( "#filtered-losses" ).val( (ui.values[ 0 ])+ " - " + (ui.values[ 1 ]))
          LossesFilter.min = ui.values[ 0 ]
          LossesFilter.max = ui.values[ 1 ]
          applyFilters()
        }
      });

      $("#points-range").slider({
        range: true,
        min: PointsFilter.min,
        max: PointsFilter.max,
        values: [ PointsFilter.min, PointsFilter.max ],
        slide: function(event, ui) {
          $( "#filtered-points" ).val( (ui.values[ 0 ])+ " - " + (ui.values[ 1 ]))
          PointsFilter.min = ui.values[ 0 ]
          PointsFilter.max = ui.values[ 1 ]
          applyFilters()
        }
      });

    $("#points_against-range").slider({
        range: true,
        min: PointsAgainstFilter.min,
        max: PointsAgainstFilter.max,
        values: [ PointsAgainstFilter.min, PointsAgainstFilter.max ],
        slide: function(event, ui) {
          $( "#filtered-points_against" ).val( (ui.values[ 0 ])+ " - " + (ui.values[ 1 ]))
          PointsAgainstFilter.min = ui.values[ 0 ]
          PointsAgainstFilter.max = ui.values[ 1 ]
          applyFilters()
        }
      });

      $("#globe-range").slider({
        range: true,
        min: GlobeFilter.min,
        max: GlobeFilter.max,
        values: [ GlobeFilter.min, GlobeFilter.max ],
        slide: function(event, ui) {
          $( "#filtered-globe" ).val( (ui.values[ 0 ])+ " - " + (ui.values[ 1 ]))
          GlobeFilter.min = ui.values[ 0 ]
          GlobeFilter.max = ui.values[ 1 ]
          applyFilters()
        }
      });


      $("#herald-range").slider({
        range: true,
        min: HeraldFilter.min,
        max: HeraldFilter.max,
        values: [ HeraldFilter.min, HeraldFilter.max ],
        slide: function(event, ui) {
          $( "#filtered-herald" ).val( (ui.values[ 0 ])+ " - " + (ui.values[ 1 ]))
          HeraldFilter.min = ui.values[ 0 ]
          HeraldFilter.max = ui.values[ 1 ]
          applyFilters()
        }
      });

      var VisibleMarkers = function() {
      var filtered = _.reject(Gmaps.map.markers, function(marker) {
          return marker.wins < WinsFilter.min || marker.wins > WinsFilter.max || marker.losses < LossesFilter.min || marker.losses > LossesFilter.max || marker.pts_for < PointsFilter.min || marker.pts_for > PointsFilter.max || marker.pts_against < PointsAgainstFilter.min || marker.pts_against > PointsAgainstFilter.max || marker.globe_rank < GlobeFilter.min || marker.globe_rank > GlobeFilter.max || marker.herald_rank < HeraldFilter.min || marker.herald_rank > HeraldFilter.max;;
       });
           return filtered
        //return Crimefiltered
       }

      var applyFilters = function() {
        _.each(Gmaps.map.markers, function(marker) {
          Gmaps.map.hideMarker(marker)
        })
        _.each(VisibleMarkers(), function(marker) {
          Gmaps.map.showMarker(marker)
        })
      };
   }
});
</script>

app/views/schools/search.html.erb
<h1>Search Results:</h1>
<% @schools.each do |school| %>
	<%= school.name %>
	<%= school.wins %>
	<%= school.losses %><br>
<% end %>
<%= link_to 'View Map', schools_path %>

app/views/schools/search.js.erb
$('body').html("<h1><%= escape_javascript(@school.title) %></h1>").append("<%= escape_javascript(@school.content) %>");

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @school.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @school.longitude %>
</p>

<p>
  <b>Wins:</b>
  <%= @school.wins %>
</p>

<p>
  <b>Losses:</b>
  <%= @school.losses %>
</p>

<p>
  <b>Pts for:</b>
  <%= @school.pts_for %>
</p>

<p>
  <b>Pts against:</b>
  <%= @school.pts_against %>
</p>

<p>
  <b>Division:</b>
  <%= @school.division %>
</p>

<p>
  <b>Big game:</b>
  <%= @school.big_game %>
</p>

<p>
  <b>Highly recruited:</b>
  <%= @school.highly_recruited %>
</p>

<p>
  <b>Globe rank:</b>
  <%= @school.globe_rank %>
</p>

<p>
  <b>Herald rank:</b>
  <%= @school.herald_rank %>
</p>

<p>
  <b>Content:</b>
  <%= @school.content %>
</p>
<%= link_to 'Back', schools_path %>